google/android-emulator-container-scripts

README.md, emu_docker.py, emu_downloads_menu.py
- Transformation done by 2to3 -w *.py
- Includes change of messaging so people doen't pass in a url vs
zipfile.
Test: Both python2 and python3 runs succeed.
=> Make scripts compatible with python 3

README.md, emu/emu_docker.py, emu/emu_downloads_menu.py, setup.py
This add the `interactive` command that allows a user to select which
system image and emulator version to use for creating a Docker image.
The system image and emulator image will be downloaded before an image
is created.
Updates the documentation with a quick start section using the
`interactive` command.
=> Add support for interactive selection of system image and emulator

README.md, emu/emu_docker.py, emu/emu_templates.py, js/src/components/emulator/emulator.js
The video bridge requires a working pulse audio driver. We now start
pulse audio with a configuration that opens up all access, and add
additional early checks to validate pulse audio configuration.
Updates the documentation with more information how to diagnose WebRTC
failures. This fixes #10.
Includes fixes for missing adb and python 2 compatibility issues.
This fixes #9.
=> Improve logging and PulseAudio support

.gitignore, .vscode/settings.json, README.md, TROUBLESHOOTING.md, configure.sh, emu/emu_docker.py, emu/emu_templates.py, setup.py
An unexpected emulator termination can leave the container in a confused state. This can cause subsequent startup failures.
Updates the documentation to explain that we cannot launch images before Oreo.
=> Update documentation and cleanup after left overs

emu/templates/Dockerfile
The latest canary build introduces a new map feature, which introduces
additional OS dependencies.
=> Update debian dependencies for canary build

README.md, js/docker/docker-compose.yaml
We now specifically request access to the devices v.s. requesting
blanket access to everything.
Resolves #16
=> Use /dev/kvm vs requesting privileged access.

js/docker/docker-compose.yaml
This is required by latest docker-compose (v 1.24.1)
https://github.com/google/android-emulator-container-scripts/issues/19
=> Updated services.emulator.devices field to be an array

README.md, aemu-container.code-workspace, create_web_container.sh, emu/templates/launch-emulator.sh, js/docker/docker-compose-with-adb.yaml
We add an additional dockerfile that exposes the adb port. This can be
used to deploy the emulator in a web container and make it accessible
over adb at the same time.
Note that this currently requires the ~/.android/adbkey to be in
existence on the machine where you are launching the web container.
The adb client used to connect to the device must have access to the
private key.
Includes a fix to forward the gRPC port when we launch without
certificates. (Needed for new canary builds)
=> Add support for exposing ADB in the webcontainer.

setup.py
'*' is not good to put in package names, as copying will often fail with
'not a regular file' (directories treated differently on different
systems, order of filenames, etc.)
=> Fix issue with package definition

js/develop.sh, js/develop/Dockerfile.mac, js/develop/Dockerfile.unix, js/src/service/auth_service.js
We now disable the login authorization workflow in developer mode.
Includes a fix where the /etc/hosts file was overwritten in unix,
causing connection failures.
We now separate the linux & mac docker files to work around the naming
of the "local" machine. See https://docs.docker.com/docker-for-mac/networking/
and https://docs.docker.com/network/network-tutorial-standalone/ for
details on docker networking differences on mac/linux.
=> Disable authorization workflow in development mode

emu/templates/Dockerfile
Using [multi-sage builds](https://docs.docker.com/develop/develop-images/multistage-build/) we can reduce the size of the images.
To give some numbers, the image size for `29 Q google_apis_playstore (x86)` and `EMU stable 29.2.1` was 4.94GB. After this changes it is 3.5GB. A reduction of 1.44GB(~30%)
Closes #40
=> Use multi-stage builds to reduce the size of the images

emu/templates/Dockerfile
This is not a big size improvement but it's completely free. We are saving ~16MB
=> Clean the apt-get caches

emu/templates/Dockerfile
Closes #43 
I added the `ca-certificates` package becase it was not installed with `--no-install-recommends`. We need it to download files over `https`
=> Add --no-install-recommends to apt-get

emu/docker_device.py
This is the default and expected behaviour when you use docker cli
Docker SDK for Python point that out at its own documentation: https://docker-py.readthedocs.io/en/stable/images.html#docker.models.images.ImageCollection.build
=> Remove intermediate containers when building the image

emu/docker_device.py, emu/emu_docker.py
I found that the `--repo` flag wasn't working. With this PR it works.
This flag is very useful. If you don't have it you need to parse the output of `emu-docker` to get the id. If we support the flag we can use the name of the image directly.
Anyway, I think that we should rename `--repo` to `--tag`. Or maybe I missundertood what `--repo` should do. If so I can refactor my PR to keep `--repo` as before and create `--tag`.
=> Implement --tag flag in create task

emu/templates/Dockerfile
This adds support for running the emulator with hardware acceleration.
It requires you to install the nvidia docker extensions.
The documentation provides details on how to use gpu acceleration.
=> Add support for NVIDIA GPUs

emu/docker_device.py, emu/emu_downloads_menu.py, emu/templates/Dockerfile, emu/templates/launch-emulator.sh, run.sh
The docker container can now report health status. The health status
indicated whether or not the emulator has successfully booted.
Currently this is retrieved by invoking ADB, this is likely going to be
deprecated soon in favor of the gRPC endpoint that is faster and more
accurate, esp with API level >28
Usage:
$ docker inspect <container-id> --format="{{json .State.Health}}"
=> Add health endpoint

README.md, emu/templates/launch-emulator.sh, run-with-gpu.sh
This updates the documentation and adds a script to launch the emulator
with hardware acceleration with NVIDIA cards.
Normal containers will default to swiftshader_indirect to prevent
incorrectly detecting the GPU drivers.
=> Update documentation for GPU usage.

TROUBLESHOOTING.md, emu/emu_docker.py, emu/emu_downloads_menu.py
We now throw an exception that is easier to understand when a wrong
zipfile is provided.
Closes #60
=> Improve error messaging.

emu/templates/Dockerfile, emu/templates/launch-emulator.sh
It seems that the switch to the nvidia container, which is based of
ubuntu, caused a different default configuration for pulse audio to be
loaded. In this configuration it is possible for the daemon to exit if
no connections are active.
We now explicitly disable this from the commandline, making sure that
pulse audio sticks around.
Fixes #58
=> Prevent early pulse audio termination.

emu/docker_device.py, tests/e2e/test_launch_containers.py
We now always fetch the proper adb version remotely. This makes sure the
code path we follow on mac is the same as linux.
Fixes 69
Test: 12 passed, 1 warnings in 244.96s (0:04:04)
=> Always use downloaded ADB

emu/templates/avd/Pixel2.avd/config.ini, emu/templates/launch-emulator.sh
This enables adding properties to the avd configuration, which in turn
can be used to override existing properties.
For example:
docker run -e
"AVD_CONFIG=hw.lcd.height=200\nhw.lcd.width=20\nhw.cpu.ncore=8\n"
--device /dev/kvm --publish 5556:5556/tcp --publish 5555:5555/tcp
aemu:aemu
Will override the lcd settings and number of cores used.
Test: 12 passed, 1 warnings in 260.52s (0:04:20)
=> Add support for config override

README.md, emu/docker_device.py, emu/emu_docker.py, emu/templates/Dockerfile, tests/e2e/test_launch_containers.py
Some users report problems when the GPU drivers are enabled but not
used. We now add a --gpu flag to explicitly enable gpu driver support.
All tests succeed.
12 passed, 1 warnings in 281.25s (0:04:41)
Partially Fixes #79
=> Explicitly request for gpu support

emu/templates/launch-emulator.sh
We disable all the buffers used by sed, that way we get the logs are
they are happening.
Pytest: 12 passed, 1 warnings in 329.67s (0:05:29)
=> Disable sed buffers

emu/templates/launch-emulator.sh
If the container is ever launched without adb keys they will be
generated. You will not be able to connect with adb if these keys
somehow survive a restart.
Pytest: 12 passed, 1 warnings in 344.02s (0:05:44)
Fixes #71
=> Erase keys before launch

README.md, emu/docker_device.py, emu/emu_docker.py, emu/emu_downloads_menu.py, tests/e2e/test_launch_containers.py, tests/test_emu_downloads_menu.py
This add support for pushing images out to a repository.
We adopted the following naming scheme for images:
{desert}-{sort}-{abi}
Where:
- desert is the desert letter
- sort is one of: *aosp*, *google*, *playstore*
- abi is one of: *x86*, *x64*, *a32*, *a64*
12 passed, 6 warnings in 160.46s (0:02:40)
=> Add support for pushing images to a repo

setup.py
The packaging module provides the versioning module. This happened to be
globally available in my development machine and was not made an
explicit dependency.
Fixes #95
=> Make packaging dependency explicit.

configure.sh, create_web_container.sh, js/README.md
1、Missing python3-venv package will cause python -m venv venv execution to fail.
Resulting in files ./venv/bin/pip and ./venv/bin/activate not being generated.
So if it fails, no need to execute setup.py
2、/bin/sh(default use dash in ubuntu) not support [[]]
3、shell [ ! expression ] and [ ! $(expression) ] should be different
=> some shell fix and doc fix

README.md, configure.sh, create_web_container.sh, emu/emu_docker.py, emu/emu_downloads_menu.py, emu/templates/Dockerfile, emu/templates/launch-emulator.sh, js/docker/docker-compose-with-adb.yaml, js/docker/docker-compose.yaml, js/docker/envoy.yaml, run-with-gpu.sh, run.sh, tests/e2e/test_launch_containers.py
This enables embedding of the private adb key, vs. the public one.
The private key will guarantee that the embedded ADB executable can
always interact with the emulator.
- Cleans up the launcher script
- Fix python2 encoding issue
- Fix adb health failure when no key was present
- Always force clean booe
Test: Tox succeeds.
Fixes: #98
=> Enable embedding of private adb key, and opening of console.

README.md, create_web_container.sh, emu/docker_device.py, emu/templates/Dockerfile, emu/templates/launch-emulator.sh, js/docker/development.yaml, js/docker/docker-compose-build.yaml, js/docker/docker-compose.yaml, js/docker/emulator.service, js/docker/production.yaml
This seperates the docker deployment and build into two steps. This
enables for easy deployment in cloud based environments.
docker-compose-build.yaml is the build script that will create a series
of named images that can be used by the docker-compose script to launch
directly.
A systemd service script is provided to bring up the containers during
boot.
Tox:
py27: commands succeeded
py37: commands succeeded
congratulations :)
=> Use docker overlays + systemd support

README.md, js/docker/envoy.Dockerfile
Pulling the latest version of envoy can easily break the default
configuration. We now pin to a specific version.
Fixes #106
=> Pin envoy to version v1.12.0

js/develop/envoy.yaml, js/package-lock.json, js/package.json, js/src/App.js, js/src/components/emulator/net/emulator_web_client.js
We now log low-level http failures, and update the ui to inform of
a failure using a Snackbar.
Envoy has deprecated a set of parameters, which broke the development
=> Log low level failures and Update envoy

README.md, run-with-gpu.sh
Running the emulator in a web environment requires binplacing of
certificates. This is done by a shell script which was not reflected in
the documentation.
Running the emulator with hardware acceleration using the nvidia base
package was missing a dash in the shell script.
Fixes #111
Fixes #110
=> Fix typo and update documentation

js/Makefile
Sed behaves differently on Darwin v.s. linux.
=> Fix Makefile to be cross platform

emu/cloud_build.py, emu/emu_docker.py, emu/emu_downloads_menu.py, emu/process.py, emu/templates/cloudbuild.README.MD
This adds support for automatically creating git commits and pushing the
commits to the repository.
This enables emu-docker to be used as part of continuous deployment.
=> Add support for git commits in cloudbuilder.

emu/templates/Dockerfile, emu/templates/Dockerfile.from_zip
This makes running emu-docker idempotent when given the same emulator
version and system image.
This will make it easier to run emu-docker in automated environments.
Test:
diff src/Dockerfile old/Dockerfile
=> Make container creation idempotent

js/android-emulator-webrtc/CONTRIBUTING.md, js/android-emulator-webrtc/LICENSE
This adds a license and contributor agreement in preparation for
moving this module to a separate repository.
=> Prepare project for separation.

create_web_container.sh, js/Makefile, js/android-emulator-webrtc/README.md, js/android-emulator-webrtc/gen_md_doc.js, js/android-emulator-webrtc/package-lock.json, js/android-emulator-webrtc/package.json, js/android-emulator-webrtc/src/components/emulator/emulator.js, js/android-emulator-webrtc/src/components/emulator/net/emulator_status.js, js/android-emulator-webrtc/src/components/emulator/net/jsep_protocol_driver.js, js/android-emulator-webrtc/src/components/emulator/net/logcat.js, js/android-emulator-webrtc/src/components/emulator/views/simple_png_view.js, js/android-emulator-webrtc/src/index.js, js/android-emulator-webrtc/webpack.config.js, js/package-lock.json, js/package.json, js/src/components/emulator_screen.js, js/src/components/logcat_view.js
We now use the published npm package v.s. building it from source.
- Reduces the installation time
- Reduces complexity of using yalc.
Test:
./create_web_container.sh creates an emulator that can be launched.
=> Use published npm package

emu/templates/launch-emulator.sh, tests/e2e/test_cloud_build.py
This enables audio processing, which in turn will allow streaming of
audio with emulator version >=30.0.22
Test: 15 passed, 6 warnings in 491.57s (0:08:11)
Fixes #133
=> Enable audio processing in emulator.

js/package-lock.json, js/package.json
The newer version of the webrtc javascript library will handle state
changes and video tags for older browsers properly.
Fixes #174
=> Fix video and connection state.

README.md, run-in-script-example.sh
This explains how to use the container in scripts when launching through
the hosted containers.
=> Add sample scripts and better quick start documentation.

emu/docker_device.py
Got an error if using the custom port in repo definition
`emu-docker create canary P --push --repo repo:5050/user/`
> Traceback (most recent call last):
>   File "/home/wert2all/work/android-emulator-container-scripts/venv/bin/emu-docker", line 33, in <module>
>     sys.exit(load_entry_point('emu-docker', 'console_scripts', 'emu-docker')())
>   File "/home/wert2all/work/android-emulator-container-scripts/emu/emu_docker.py", line 271, in main
>     args.func(args)
>   File "/home/wert2all/work/android-emulator-container-scripts/emu/emu_docker.py", line 104, in create_docker_image
>     device.push(img)
>   File "/home/wert2all/work/android-emulator-container-scripts/emu/docker_device.py", line 136, in push
>     repo, tag = self.tag.split(":")
> ValueError: too many values to unpack …
=> Fixed repo with port fail

README.md
There were some misspelled words and incorrect/missing port numbers.
=> Fix typos in documentation.

README.md, emu/templates/launch-emulator.sh, js/README.md, js/turn/README.MD, js/turn/turn.py, run-in-script-example.sh, run-with-gpu.sh, run.sh
This updates the documentation and adds more details on how to configure
your own TURN server if needed. A TURN server is needed if the emulator
is hidden behind a VPN that does not permit UDP packets to go through.
We modify the launcher to make it easier to pass in the turn
configuration at container launch time.
=> Update documentation for TURN usage.

emu/cloud_build.py
This enables all containers to be created concurrently.
=> Enable concurrent cloud builds.

emu/emu_downloads_menu.py, emu/templates/Dockerfile
This allows the repo naming to include an api level value if present in the properties file of the system image.
Does this really even need special behavior for the empty case? That seems unlikely to not have an api level value.
Potentially a breaking change for people depending on the existing format pattern.
closes #190
=> Add api level integer to repository naming

emu/templates/launch-emulator.sh
Exec replaces the current running process, this makes sure that the
emulator traps the INT signal again, vs the shell.
=> Reintroduce missing exec.

emu/docker_device.py, emu/emu_docker.py
We now force the --extra flag to be the last flag that is parsed. This
makes sure we correctly pass the additional parameters, without running
into strange argparser behavior.
Fixes #194
=> Force argparser to parse --extra correctly.

README.md
The image specified didn't exist and the docker error message was a bit unclear. A real image is shown slightly lower down so I changed the example to use this image
=> Update example to use real image

js/package-lock.json, js/package.json
This bumps the version of the android emulator webrtc library to
1.0.3 which supports touch events.
Note: This requires emulator 30.1.4 or later.
=> Enable touch events in javascript example.

setup.py
We did not properly update setup.py, causing missing templates when
a full install was executed.
Fixes #218
=> Fix missing templates from setup.py

emu/emu_docker.py, emu/emu_downloads_menu.py
You can now build docker containers from the emulator builds that are
hosted on the public ci server
(https://ci.android.com/builds/branches/aosp-emu-master-dev/grid?)
=> Add support for building images from emulator build ids

README.md, cloud-init/README.MD, cloud-init/cloud-init
This provides a cloud-init script that is capable of launching the
emulator in a cloud environment. It will configure the emulator and make
adb and gRPC available.
=> Provide cloud-init scripts for cloud providers

emu/emu_downloads_menu.py
When the system image had multiple urls for multiple OSes we always
picked the first url, then later we filtered it out if it contained the
"windows" or "darwin" strings. Now we look for the "linux" url first.
"emu-docker list" shows the following additional images:
SYSIMG Q android x86_64 29 https://dl.google.com/android/repository/sys-img/android/x86_64-29_r07-linux.zip
SYSIMG Q android x86 29 https://dl.google.com/android/repository/sys-img/android/x86-29_r07-linux.zip
SYSIMG Q google_apis_playstore x86_64 29 https://dl.google.com/android/repository/sys-img/google_apis_playstore/x86_64-29_r08-linux.zip
SYSIMG Q google_apis_playstore x86 29 https://dl.google.com/android/repository/sys-img/google_apis_playstore/x86-29_r08-linux.zip
SYSIMG R google_apis_playstore x86_64 30 …
=> Do not give up on images where first zip is not for Linux

js/develop.sh, js/develop/envoy.yaml, js/package-lock.json, js/package.json, js/src/App.js
This updates the android-emulator-webrtc pacakge to a version that fixes
a series of issues:
- Touch events should now be handled properly accross phones/tablets
- Workaround for older emulators that can deliver ice candidates out of
order
- Updates all javascript packages to fix security concerns.
Updates the envoy development yaml to run the video bridge separately
from the emulator. This is mainly to make it easier to develop issues
inside the bridge.
Fixes #210
=> Fix webrtc connection issues.

js/package-lock.json, js/package.json
We update to a newew package version that contains a series of
concurrency fixes that can arise with emulator builds <7118781
Fixes: #210
=> Update android-emulator-webrtc package.

cloud-init/README.MD, cloud-init/cloud-init, emu/cloud_build.py, emu/docker_device.py, emu/emu_docker.py, emu/emu_downloads_menu.py, emu/templates/launch-emulator.sh, tests/e2e/test_cloud_build.py, tests/e2e/test_launch_containers.py
This updates the cloud-init scripts to support multiple emulators to run side by side.
=> Update cloud-init for multi emulator deployment

README.md
x64 is correct for the docker images, but the emu-docker command only knows x86_64
=> Clarify available architectures

emu/emu_downloads_menu.py, emu/templates/Dockerfile.system_image
Since the current version didn't support the newest versions of emulators (using interactive mode), I've added a line to add the support in emu_downloads_menu.py.
However, I have trouble concerning the unzipping of the image through the default Docker system image template. Apparently, there is some bug in the latest unzip version (6.0-r9) to detect zip bombs. This version was considering the Android 12 system images' zips as possibles zip bombs. I fixed it by downgrading the alpine version to v3.3 considering it uses the unzip version 6.0-r1. I've not tested using some new alpine versions rather than the latest one to verify in which version of alpine and unzip this issue started to happen.
Everything seems to be working though.
=> Add support to Android 12 (S) images

emu/templates/launch-emulator.sh
Calling the 'run' function inside the launch-emulator.sh script causes
issue with parameter quoting, which in turn breaks the usage of the
`TURN` environment variable.
We now directly call exec, vs the run function.
=> Directly call exec to launch the emulator

README.md, emu/templates/launch-emulator.sh, setup.py
Several fixes to make it work out of the box
- add dependencies needed for requests (urllib3 and markupsafe)
- add a ANDROID_AVD_HOME, otherwise the AVD were not found
- clean up a few things in the doc
=> Proposed fixes 042023

js/docker/envoy.yaml
This activates tls so we can retrieve the certs over https
=> Enable TLS for firebase

emu/templates/launch-emulator.sh
Regression introduced in: https://github.com/google/android-emulator-container-scripts/pull/227
=> Fix regression and use symlink instead of env var

emu/android_release_zip.py, emu/emu_downloads_menu.py
Adding support to download and use `google_atd` system images:
```
(venv) ➜  android-emulator-container-scripts git:(master) ✗ emu-docker list | grep google_atd
SYSIMG R google_atd x86 30 https://dl.google.com/android/repository/sys-img/google_atd/x86-30_r01.zip
SYSIMG S google_atd x86_64 31 https://dl.google.com/android/repository/sys-img/google_atd/x86_64-31_r01.zip
```
=> [emu] add support for google_atd

pyproject.toml
As seen in https://github.com/google/android-emulator-container-scripts/issues/382
=> Update docker-py dependency because of breakage with request 2.32
