TROUBLESHOOTING.md

Fix layout issue in markdown document.

---

configure.sh
create_web_container.sh
emu/emu_docker.py
emu/templates/Dockerfile
emu/templates/avd/Pixel2.avd/config.ini
js/src/components/emulator_screen.js

- Embed curl in the container for turn support through curl
- Reduce the size of the sd card. This will reduce the boot times for
certain images.
- Make shell scripts posix compliant, they now work under /bin/dash
- Select proper python interpreter in config.
- Do not use fallback but png view in javascript.
Fallback can behave in an unexpected fashion if your webrtc
configuration relies on turn, and your turn service happens to be
misconfigured.

Fix a series of small issues.

---

README.md
TROUBLESHOOTING.md

Adds a section around using the virtual environment and recommend using
the virtual environment. This will make sure users do not pollute their
python environment and run into path issues.
Closes #30

Update Known Issues document.

---

emu/emu_docker.py
emu/emu_downloads_menu.py

The commandline can now dynamically download an emulator zip and system
image zip from the list of publicly available images.
This makes it easier to script container building. For example:
$ emu-docker create canary Q
Will download the latest canary build and "Q" image to construct
a docker container.

Enable install by emulator channel and system image.

---

create_web_container.sh

Newer versions of adb no longer generate a public key. We now create the
public key if needed, this makes sure uses can connect to the created
container with adb if needed.
Fixes #59

Generate public adbkey if it does not exist

---

emu/docker_device.py
emu/templates/Dockerfile

Install adb in the correct location

---

README.md

Correct port number described in README.md

---

emu/emu_downloads_menu.py

This gets the container scripts ready for the next release.

Add support for R

---

README.md
js/android-emulator-webrtc/Makefile
js/android-emulator-webrtc/eslint_prefix.py
js/develop/Dockerfile.mac
js/develop/Dockerfile.unix

Fixes undefined reference errors.

Fix eslint issues

---

setup.py

This pins jinja to 2.11.1
Fixes #122

Pin jinja version.

---

README.md

See: https://github.com/google/android-emulator-container-scripts/issues/144

Add adb connection precision

---

run-with-gpu.sh

There was an incorrect mapping in the gpu launcher script
Fixes #152

Fix incorrect port mapping in gpu script

---

emu/docker_device.py
emu/templates/emulator.README.MD

This adds a readme to the docker container describing what is in the
container and how to use it.

Add a README.MD to the docker container.

---

emu/template_writer.py

Encode template writer as utf-8

---

emu/docker_config.py

Reload the DockerConfig before changing it

---

README.md
REGISTRY.MD

This updates the examples and latest registry with the tags based upon
api level.

Update document with updated tags.

---

js/package-lock.json
js/package.json
js/src/components/emulator_screen.js

The newer version of the emulator library has support for gps. This
example demonstrates how you can get the current location and use it to
set the location in the emulator.
Note: Android uses a multitude of ways to derive the location and the
location service might get confused if you "jump" around the earth quickly.

Add sample of GPS

---

README.md
REGISTRY.MD

=================================
This updates the registry links to the 30.1.2 emulator release.

Emulator version: 30.1.2

---

README.md
emu/templates/Dockerfile
emu/templates/Dockerfile.from_zip
emu/templates/launch-emulator.sh

This add support for mounting a data partition that will be used for the
AVD definition. This enables you to  mount a tmpfs which can give
increased performance.

Support mounting data partition

---

emu/templates/launch-emulator.sh
js/package-lock.json
js/package.json

This lowers the logging level and updates the android-emulator-webrtc package.

Reduce logging and improve webrtc connections.

---

emu/emu_downloads_menu.py

Adds support for creating containers using the Android-TV emulator images.

Add Android-TV support

---

js/jwt-provider/requirements.txt

Fix version to Flask-HTTPAuth==4.4.0

---

LICENSE

Adding back the LICENSE from last commit 7b465e96c79db9b483a53c07eb11…
Issue: https://github.com/google/android-emulator-container-scripts/issues/354

Adding back the LICENSE 
